### ISSUE TITLE
Missing module docstring

### ISSUE THREAD

**Issue by Zeroocooloverride** [problemsolvewithridoy/Phone-number-location-tracker-using-python#1]
cant find modul in line 6 (key)  ??

**Comment by problemsolvewithridoy** [comment]
> cant find modul in line 6 (key) ??

Now need to collect Geocoder API Key from https://opencagedata.com/
@Zeroocooloverride Thank you

**Comment by Zeroocooloverride** [comment]
Thanks a lot! really much appreciate!

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
