### ISSUE TITLE
from myphone import key ModuleNotFoundError: No module named 'myphone'

### ISSUE THREAD

**Issue by MrS3rv3r404** [problemsolvewithridoy/Phone-number-location-tracker-using-python#3]
from myphone import key
ModuleNotFoundError: No module named 'myphone'

Can you fix it

**Comment by problemsolvewithridoy** [comment]
@MrS3rv3r404 Where you found "myphone"? i don't understand 

you need to install : 



import phonenumbers
from phonenumbers import geocoder
from phonenumbers import carrier
import opencage
from opencage.geocoder import OpenCageGeocode
import folium

**Comment by MrS3rv3r404** [comment]
i edited the main.py file and i filled the key with my api geocoder.  and after I run an error appears

**Comment by MrS3rv3r404** [comment]
![Uploading Screenshot_2023-08-07-09-29-38-829_com.termux.jpg…]()

**Comment by MrS3rv3r404** [comment]
$ python3 main.py
Traceback (most recent call last):                        File "/data/data/com.termux/files/home/Phone-number-location-tracker-using-python/main.py", line 6, in <module>                                                           from myphone import key
ModuleNotFoundError: No module named 'myphone'

**Comment by problemsolvewithridoy** [comment]
please copy this code and run it, your error will be solved 😀

import phonenumbers
from phonenumbers import geocoder
from phonenumbers import carrier
import opencage
from opencage.geocoder import OpenCageGeocode
import folium

key = "your key" #Geocoder API Key need to paste here "your key"
number = input("please giver your number: ")
new_number = phonenumbers.parse(number)
location = geocoder.description_for_number(new_number, "en")
print(location)

service_name = carrier.name_for_number(new_number,"en")
print(service_name)

geocoder = OpenCageGeocode(key)
query = str(location)
result = geocoder.geocode(query)
#print(result)

lat = result[0]['geometry']['lat']
lng = result[0]['geometry']['lng']

print(lat,lng)

my_map = folium.Map(location=[lat,lng], zoom_start=9)
folium.Marker([lat, lng], popup= location).add_to(my_map)

my_map.save("location.html")

print("location tracking completed")
print("Thank you")

**Comment by MrS3rv3r404** [comment]
It's work bro but not accurated  location for tracking phone number

**Comment by problemsolvewithridoy** [comment]
It's depended on your API bro. 🙂
